Merge Work into Develop
r-wambui/bucket_list pull request #2
Opened 2017-06-12 12:47 UTC by r-wambui

This PR contains a merge from work to develop,

2017-06-12 14:10 UTC, dmigwi requested changes
Please check the following
- You only need one instance of `app=Flask(__name__)`. Import the one instance wherever you need it...
-   To many if statements make your code look poor. Avoid nesting if statements..
- Properly space your functions
- Delete all unnecessary files from github before adding them to .gitignore file..

2017-06-12 14:10 UTC, dmigwi commented on .gitignore
> +__pycache__
You need to delete all this `.pyc` files from github so that your `.gitignore` can block them. Ensure you delete all `.pyc` and `.DS_Store` files..

2017-06-12 14:10 UTC, dmigwi commented on app/models.py
> +            return None
You could merge the above two exceptions into a single line as 
``` 
except Signature, BadSignature :
      return None
```
Checkout https://stackoverflow.com/questions/6470428/catch-multiple-exceptions-in-one-line-except-block

2017-06-12 14:10 UTC, dmigwi commented on app/models.py
> +    done = db.Column(db.Boolean, default= False)
In your models there seems to be several common fields..
you could create a base model class with all common fields. The base model could be imported by other models i.e.
```
class baseModel(db.Model):
       __abstract__=True // so that flask doesn't create a table called baseModel
       id = db.Column(db.Integer, primary_key=True)
       name = db.Column(db.String)
       date_created = db.Column(db.DateTime, default=datetime.now, nullable=False)
       date_modified = db.Column(db.DateTime, default=datetime.now, nullable=False)
       created_by = db.Column(db.Integer, db.ForeignKey("user_model.id"))
```
Now import the baseModel in all other model you've created

```
class Bucketlist(baseModel):
        __tablename__ = "bucketlist"
        bucketitems = db.relationship("BucketlistItem", backref="bucketlist", lazy="dynamic")
```
do this for all other models only adding unique fields only..

For more information check my implementation on the same https://github.com/andela-dmigwi/A-BucketList/blob/master/app/models.py

2017-06-12 14:10 UTC, dmigwi commented on app/models.py
> +    ___tablename__ = "bucketlist_item"
table name should  be written as `__tablename__` not what you've written in line 53, 65 and 14

2017-06-12 14:10 UTC, dmigwi commented on app/models.py
> +
Your code doesn't look clean and neat. Between functions there should be a space of two lines only. And the last line in a python file of code should  be a blank line.. Please install *anaconda* python plugin in sublime. It should highlight some of this pep8 errors..

2017-06-12 14:10 UTC, dmigwi commented on app/resources/auth.py
> +
Because of the return statement in line 34 you don't need an else block..
rewrite as below..
```
           if person:
                    return {'error': "User already exist"}, 409
            user = UserModel(username=args.username, password=args.password)
            db.session.add(user)
            db.session.commit()    
            return {'message': 'User created successfully'}, 201
```

2017-06-12 14:10 UTC, dmigwi commented on app/resources/auth.py
> +            db.session.commit()
check my implementation on how I created a single method called `save()` in the model that does what line 36 and 37 does..
https://github.com/andela-dmigwi/A-BucketList/blob/master/app/models.py

2017-06-12 14:10 UTC, dmigwi commented on app/resources/bucketlist.py
> +app.config.from_object('config.DevelopmentConfig')
This is wrong `app = Flask(__name__)`. You should only have one instance of that code in your whole flask. Creating several instances of that app will cause problems later while trying to synchronize stuffs in you project. First instance is in` app/models.py`.
Delete one instance and import the other instance.**AVOID CIRCULAR IMPORTS**, they will mess you up very bad..

2017-06-12 14:10 UTC, dmigwi commented on app/resources/bucketlist.py
> +
- Delete all commented code.
- Your code doesn't have any doc strings
- Also you don't need the else statement in line 50 as the else block will never be executed if the bucket exist. Check the example I demonstrated above..

2017-06-12 14:10 UTC, dmigwi commented on app/resources/bucketlist.py
> +                            "name": bucketlist.name,
Avoid nesting if statements. Check code between line 67 and line 70. The first if statement doesn't make sense, remove it ASAP. This is how you create untraceable bugs..

2017-06-12 14:10 UTC, dmigwi commented on app/resources/bucketlist.py
> +
line 104 to 106 can also be rewritten as
```buckets, next_url, prev_url = [ ], None, None```

2017-06-12 14:10 UTC, dmigwi commented on app/resources/bucketlist.py
> +
- Avoid this style of writting code. Please do not nest if statement like in the code in line 158 to line 162.
- Also the else statement at line 164 doesn't make sense..  Remove it

2017-06-12 14:10 UTC, dmigwi commented on app/resources/bucketlist.py
> +            return ({"error": "bucketlist does not exist."}, 404)
the code between line 175 and 188 should be written as below..
```
@auth.login_required
def delete(self, id):
    bucketlist = Bucketlist.query.filter_by(id=id).first()
    if not bucketlist:
        return ({"error": "bucketlist does not exist."}, 404)
    if bucketlist.created_by == g.user.id:
        db.session.delete(bucketlist)
        db.session.commit()
        return ({"message": "delete successful"}, 204)
    return ({"error": "You can only delete your own buckelist."}, 400)
```

Avoid unnecessary if statements. You see the code looks cleaner..!!!

2017-06-12 14:10 UTC, dmigwi commented on app/resources/item.py
> +            return ({"error": "You can only delete your own buckelist."}, 401)
Never push your database to github. Delete `app/test.db` file from github and add it to your gitignore

2017-06-12 14:10 UTC, dmigwi commented on config.py
> +
The is **VERY VERY** wrong !!!!!. You should not have more than one instances of `app = Flask(__name__)`.

2017-06-12 14:10 UTC, dmigwi commented on config.py
> +
`SECRET_KEY = 'iamthekeytothistokenthatiwantyoutouse'` seems to be common. Add it to BaseConfig class and remove it all classes... Actually you have it in the BaseConfig class then why are you repeating it the classes that inherit from baseConfig????????

2017-06-12 14:10 UTC, dmigwi commented on manage.py
> +app.config.from_object('config.DevelopmentConfig')
The is VERY VERY wrong !!!!!. You should not have more than one instances of app = Flask(__name__).

2017-06-12 14:10 UTC, andela-dmigwi commented on migrations/versions/ce3e8bc1ce0f_.py
> +"""empty message
Migration folder should never be pushed to github. Delete it from github and and add it to gitignore.
Procedure to regenerate the migration files should be put in your readme file..

2017-06-12 14:10 UTC, andela-dmigwi commented on run.py
> +    app.run(debug=True)
Your spacing is incorrect. checkout https://www.python.org/dev/peps/pep-0008/#blank-lines..

2017-06-18 14:57 UTC, r-wambui commented on .gitignore
> +__pycache__
Resolved, deleted all the unnecessary files from the repo.

2017-06-18 15:00 UTC, r-wambui commented on app/models.py
> +
Resolved. Installed flake8 which checks fro pep8 and also used anaconda to autocheck pep8 errors

2017-06-18 15:02 UTC, r-wambui commented on app/models.py
> +    ___tablename__ = "bucketlist_item"
Resolved.

2017-06-18 15:04 UTC, r-wambui commented on run.py
> +    app.run(debug=True)
Resolved

2017-06-18 15:04 UTC, r-wambui commented on manage.py
> +app.config.from_object('config.DevelopmentConfig')
Resolved

2017-06-18 15:06 UTC, r-wambui commented on config.py
> +
Resolved.

2017-06-18 15:06 UTC, r-wambui commented on app/resources/item.py
> +            return ({"error": "You can only delete your own buckelist."}, 401)
Resolved. Added *.db to gitignore

2017-06-18 15:09 UTC, r-wambui commented on app/resources/bucketlist.py
> +                            "name": bucketlist.name,
Resolved

2017-06-18 15:11 UTC, r-wambui commented on app/resources/bucketlist.py
> +
Resoved.

2017-06-18 15:13 UTC, r-wambui commented on app/resources/auth.py
> +
Resolved.

2017-06-18 15:14 UTC, r-wambui commented on app/resources/bucketlist.py
> +
Resolved.

2017-06-18 15:16 UTC, r-wambui commented on app/resources/bucketlist.py
> +
Noted and Resolved.

2017-06-27 07:58 UTC, merged